web-server:
  hosts:
    kot-labs-web.kot-labs.com:
      host_port: 1001
web-apps:
  vars:
    base_image_url: "public.ecr.aws/flynshue"
    image: "{{ base_image_url }}/{{ image_name }}:{{ image_version }}"
    publish_ports: "{{ host_port }}:{{ container_port }}"
  hosts:
    test-plate-stack.kot-labs.com:
      host_port: 3001
      container_name: test-plate-stack
      container_port: 3000
      image_name: plate-stack
      image_version: v0.0.2
    test-cod.kot-labs.com:
      host_port: 5000
      container_name: test-cod-maps
      container_port: 5000
      image_name: cod-maps
      image_version: v0.0.1